saturn/apps/job_application/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

import job_application.views


urls_jobs_patterns = [

    # URLS FOR JOB APPLICATIONS
    # url(r'^$', job_application.views.ApplicationsView.as_view(), name='home-application'),
    url(r'^job/create/$', job_application.views.JobApplFormView.as_view(), name='create'),
    url(r'^job/list/$', job_application.views.ApplicationsView.as_view(), name='list'),
]

saturn/apps/profiles/urls.py
from django.conf.urls import url

import curriculums.views

url_profile_patterns = [

    # URLS FOR CURRICULUMS
    url(r'^$', curriculums.views.ResumeView.as_view(), name='home-cv'),
    url(r'^resume/(?P<slug>[a-zA-Z0-9-_]+)/$', curriculums.views.JobsView.as_view(), name='resume'),
    url(r'^jobs/(?P<slug>[a-zA-Z0-9-_]+)/$', curriculums.views.JobsView.as_view(), name='jobs'),
    url(r'^education/(?P<slug>[a-zA-Z0-9-_]+)/$', curriculums.views.ResumeView.as_view(), name='education'),

]

saturn/saturn/urls.py
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.conf import settings

import accounts.views
import profiles.urls
import curriculums.urls
import addresses.urls
import job_application.urls

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # LINEZAP PORTAL
    url(r'^$', csrf_exempt(accounts.views.HomepageView.as_view()), name='homepage'),
    url(r'^login/$', accounts.views.LoginView.as_view(), name='login'),
    url(r'^sign-in/$', accounts.views.LoginAjaxView.as_view(), name='login-ajax'),

    url(r'^sign-up/$', accounts.views.SignUpView.as_view(), name='sign-up'),
    url(r'^register/$', accounts.views.SignUpAjaxView.as_view(), name='signup-ajax'),

    url(r'^logout/$', accounts.views.LogoutView.as_view(), name='logout'),

    # PROFILES
    url(r'^profile/', include(profiles.urls.url_profile_patterns, namespace='profile')),

    # CURRICULUMS
    url(r'^curriculum/', include(curriculums.urls.url_cv_patterns, namespace='cv')),

    # ADDRESSES
    url(r'^address/', include(addresses.urls.url_adresses_patterns, namespace='address')),

    # JOB APPLICATIONS AND WORKFLOWS
    url(r'^applications/', include(job_application.urls.urls_jobs_patterns, namespace='applications')),

]

saturn/templates/navigation/sidebar.html
{% load i18n %}

<aside class="sidebar-left">
    <ul class="side-nav fixed clearfix left" id="nav-mobile">
        <li>
            <ul class="collapsible" data-collapsible="accordion">
                <li>
                    <div class="collapsible-header waves-effect"><i class="zmdi zmdi-apps zmdi-hc-fw"></i>Dashboards <i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="{% url 'cv:home-cv' %}">{% trans "Curriculum" %}</a>
                            </li>
                            <li>
                                <a href="analytics.html">Analytics</a>
                            </li>
                            <li>
                                <a href="server.html">Server</a>
                            </li>
                            <li>
                                <a href="sales.html">Sales</a>
                            </li>
                            <li>
                                <a href="social.html">Social</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header waves-effect"><i class="zmdi zmdi-google-pages "></i>Pages<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="magazine.html">Magazine</a></li>
                            <li><a href="blog.html">Blog</a></li>
                            <li><a href="pricing.html">Pricing</a></li>
                            <li><a href="timeline.html">Timeline</a></li>
                            <li><a href="feed.html">Feed</a></li>
                            <li><a href="profile.html">Profile</a></li>
                            <li><a href="calendar.html">Calendar</a></li>
                            <li><a href="mail.html">Mail</a></li>
                            <li><a href="login-signup.html">Sign Up</a></li>
                            <li><a href="login-signIn.html">Sign In</a></li>
                            <li><a href="lock-screen.html">Lock Screen</a></li>
                            <li><a href="404.html">404</a></li>
                            <li><a href="500.html">500</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header waves-effect"><i class="zmdi zmdi-shopping-cart"></i>E-commerce<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="cards.html">Cards</a></li>
                            <li><a href="carousel.html">Carousel</a></li>
                            <li><a href="product-panel.html">Product Panel</a></li>
                            <li><a href="products.html">Products</a></li>
                            <li><a href="orders.html">Orders</a></li>
                            <li><a href="discounts.html">Discounts</a></li>
                            <li><a href="invoice.html">Invoice</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header waves-effect"><i class="zmdi zmdi-view-list zmdi-hc-fw"></i>Forms<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="elements.html">Elements</a></li>
                            <li><a href="extra.html">Extra</a></li>
                            <li><a href="wysiwyg.html">Wysiwyg Editors</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="layouts.html" class="collapsible-header"><i class="zmdi zmdi-view-quilt"></i>Layouts</a>
                </li>
                <li>
                    <div class="collapsible-header waves-effect"><i class="zmdi zmdi-palette zmdi-hc-fw new-additions" data-new="2"></i>UI Elements<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="cards.html">Cards</a></li>
                            <li><a href="buttons.html">Buttons</a></li>
                            <li><a href="breadcrumb.html">Breadcrumbs</a></li>
                            <li><a href="colors.html">Colors</a></li>
                            <li><a href="collections.html">Collections</a></li>
                            <li><a href="typography.html">Typography</a></li>
                            <li><a href="widgets.html">Widgets</a></li>
                            <li><a href="navbar.html">Navbars</a></li>
                            <li><a href="footers.html">Footers</a></li>
                            <li><a href="snackbars-toasts.html">Snackbars & toasts<span class="new badge sidenav-badge"></span></a></li>
                            <li><a href="tooltips.html">Tooltips<span class="new badge sidenav-badge"></span></a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header waves-effect">
                        <i class="zmdi zmdi-eye zmdi-hc-fw"></i>Icons <i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i>
                    </div>
                    <div class="collapsible-body icons-li">
                        <ul>
                            <li>
                                <a href="fontello.html" class="collapsible-header"><i class="zmdi zmdi-eye" ></i>Fontello</a>
                            </li>
                            <li>
                                <a href="google_material_design.html" class="collapsible-header" ><i class="zmdi zmdi-eye" ></i>Material Icons</a>
                            </li>
                            <li>
                                <a href="material_design_iconic.html" class="collapsible-header"><i class="zmdi zmdi-eye"></i>M D Iconic</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header waves-effect"><i class="zmdi zmdi-collection-folder-image"></i>Media<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="sliders.html">Sliders</a></li>
                            <li><a href="gallery.html">Gallery</a></li>
                            <li><a href="image-hover.html">Image Hover Effects</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
    </ul>
</aside>
<script>
    root();
    $('.button-collapse').sideNav({
        menuWidth: 240, // Default is 240
        edge: typeof ThemeSettings != "undefined" && ThemeSettings.getCookie('reading-direction') == 'rtl' ? 'right' :'left', // Choose the horizontal origin
        closeOnClick: false // Closes side-nav on <a> clicks, useful for Angular/Meteor
    });
    $('.collapsible').collapsible();
</script>

saturn/templates/navigation/topbar.html
{% load i18n %}
{% load static from staticfiles %}
{% load statici18n %}
{% load urlhelpers %}

<nav class="horizontal-nav hide-on-med-and-down grey darken-1">
    <div class="nav-wrapper ">
        <ul class="">
            <li><a href="{% url 'cv:home-cv' %}">{% trans "Curriculum" %}</a></li>
            <li>
                <a class="dropdown-button waves-effect" href="#!" data-activates="e_commerce-items">Jobs<i class="material-icons right">arrow_drop_down</i></a>
                <ul id="e_commerce-items" class="dropdown-content">
                    <li><a href="#">Search</a></li>
                    <li><a href="#">Proposals</a></li>
                </ul>
            </li>
            <li>
                <a class="dropdown-button waves-effect" href="#!" data-activates="tables-items">Recruitment<i class="material-icons right">arrow_drop_down</i></a>
                <ul id="tables-items" class="dropdown-content">
                    <li><a href="{% url 'applications:create' %}">{% trans "Create job application" %}</a></li>
                    <li><a href="{% url 'applications:list' %}">{% trans "My application List" %}</a></li>
                    <li><a href="#">Manage Recruitment workflows</a></li>
                </ul>
            </li>
            <li>
                <a class="dropdown-button waves-effect" href="#!" data-activates="forms-items">Connections<i class="material-icons right">arrow_drop_down</i></a>
                <ul id="forms-items" class="dropdown-content">
                    <li><a href="elements.html">My network</a></li>
                    <li><a href="extra.html">Extra</a></li>
                </ul>
            </li>
            <li><a href="layouts.html">Notifications</a></li>
        </ul>
    </div>
</nav>
<ul class="side-nav fixed clearfix left  hide-on-large-only" id="nav-mobile">
    <li>
        <ul class="collapsible" data-collapsible="accordion">
            <li>
                <div class="collapsible-header waves-effect"><i class="zmdi zmdi-apps zmdi-hc-fw black-text"></i>Dashboards <i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                <div class="collapsible-body">
                    <ul>
                        <li>
                            <a href="general.html">General</a>
                        </li>
                        <li>
                            <a href="analytics.html">Analytics</a>
                        </li>
                        <li>
                            <a href="server.html">Server</a>
                        </li>
                        <li>
                            <a href="sales.html">Sales</a>
                        </li>
                        <li>
                            <a href="social.html">Social</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <div class="collapsible-header waves-effect"><i class="zmdi zmdi-google-pages black-text"></i>Pages<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="magazine.html">Magazine</a></li>
                        <li><a href="blog.html">Blog</a></li>
                        <li><a href="pricing.html">Pricing</a></li>
                        <li><a href="timeline.html">Timeline</a></li>
                        <li><a href="feed.html">Feed</a></li>
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="calendar.html">Calendar</a></li>
                        <li><a href="mail.html">Mail</a></li>
                        <li><a href="login-signup.html">Sign Up</a></li>
                        <li><a href="login-signIn.html">Sign In</a></li>
                        <li><a href="lock-screen.html">Lock Screen</a></li>
                        <li><a href="404.html">404</a></li>
                        <li><a href="500.html">500</a></li>
                    </ul>
                </div>
            </li>
            <li>
                <div class="collapsible-header waves-effect">
                    <i class="zmdi zmdi-chart zmdi-hc-fw black-text"></i>Charts <i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i>
                </div>
                <div class="collapsible-body">
                    <ul>
                        <li>
                            <a href="amCharts.html" class="collapsible-header" ><i class="zmdi zmdi-chart" ></i>AmCharts</a>
                        </li>
                        <li>
                            <a href="c3Charts.html" class="collapsible-header"><i class="zmdi zmdi-chart"></i>C3 Charts</a>
                        </li>
                        <li>
                            <a href="flotCharts.html" class="collapsible-header"><i class="zmdi zmdi-chart"></i>Flot Charts</a>
                        </li>
                        <li>
                            <a href="highCharts.html" class="collapsible-header"><i class="zmdi zmdi-chart"></i>HighCharts</a>
                        </li>
                        <li>
                            <a href="morrisCharts.html" class="collapsible-header"><i class="zmdi zmdi-chart"></i>Morris Charts</a>
                        </li>
                        <li>
                            <a href="nvd3Charts.html" class="collapsible-header"><i class="zmdi zmdi-chart"></i>NvD3 Charts</a>
                        </li>
                        <li>
                            <a href="sparklineCharts.html" class="collapsible-header"><i class="zmdi zmdi-chart"></i>Sparkline Charts</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <div class="collapsible-header waves-effect"><i class="zmdi zmdi-shopping-cart black-text"></i>E-commerce<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="cards.html">Cards</a></li>
                        <li><a href="carousel.html">Carousel</a></li>
                        <li><a href="product-panel.html">Product Panel</a></li>
                        <li><a href="discounts.html">Discounts</a></li>
                        <li><a href="invoice.html">Invoice</a></li>
                    </ul>
                </div>
            </li>
            <li>
                <div class="collapsible-header waves-effect"><i class="zmdi zmdi-grid"></i>Tables<i class="zmdi zmdi-chevron-down black-text"></i><i class="zmdi zmdi-chevron-up"></i></div>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="data-tables.html">Data Tables</a></li>
                        <li><a href="tables.html">Regular Tables</a></li>
                    </ul>
                </div>
            </li>
            <li>
                <div class="collapsible-header waves-effect"><i class="zmdi zmdi-view-list zmdi-hc-fw"></i>Forms<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="elements.html">Elements</a></li>
                        <li><a href="extra.html">Extra</a></li>
                        <li><a href="wysiwyg.html">Wysiwyg Editors</a></li>
                    </ul>
                </div>
            </li>
            <li>
                <a href="layouts.html" class="collapsible-header"><i class="zmdi zmdi-view-quilt black-text"></i>Layouts</a>
            </li>
            <li>
                <div class="collapsible-header waves-effect"><i class="zmdi zmdi-palette zmdi-hc-fw black-text"></i>UI Elements<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="cards.html">Cards</a></li>
                        <li><a href="buttons.html">Buttons</a></li>
                        <li><a href="breadcrumb.html">Breadcrumbs</a></li>
                        <li><a href="colors.html">Colors</a></li>
                        <li><a href="collections.html">Collections</a></li>
                        <li><a href="typography.html">Typography</a></li>
                        <li><a href="widgets.html">Widgets</a></li>
                        <li><a href="navbar.html">Navbars</a></li>
                        <li><a href="footers.html">Footers</a></li>
                    </ul>
                </div>
            </li>
            <li>
                <div class="collapsible-header waves-effect">
                    <i class="zmdi zmdi-eye zmdi-hc-fw black-text"></i>Icons <i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i>
                </div>
                <div class="collapsible-body icons-li">
                    <ul>
                        <li>
                            <a href="fontello.html" class="collapsible-header"><i class="zmdi zmdi-eye" ></i>Fontello</a>
                        </li>
                        <li>
                            <a href="google_material_design.html" class="collapsible-header" ><i class="zmdi zmdi-eye" ></i>Material Icons</a>
                        </li>
                        <li>
                            <a href="material_design_iconic.html" class="collapsible-header"><i class="zmdi zmdi-eye"></i>M D Iconic</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <div class="collapsible-header waves-effect"><i class="zmdi zmdi-collection-folder-image black-text"></i>Media<i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="sliders.html">Sliders</a></li>
                        <li><a href="gallery.html">Gallery</a></li>
                        <li><a href="image-hover.html">Image Hover Effects</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </li>
</ul>
<script>
    root();
    $('.dropdown-button').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: true, // Does not change width of dropdown to that of the activator
        hover: true, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: true, // Displays dropdown below the button
        alignment: 'left' // Displays dropdown with edge aligned to the left of button
    });
    $('.button-collapse').sideNav({
        menuWidth: 240, // Default is 240
        edge: 'left', // Choose the horizontal origin
        closeOnClick: false // Closes side-nav on <a> clicks, useful for Angular/Meteor
    });
    $('.collapsible').collapsible();
</script>

saturn/templates/navigation/topnav.html
{% load i18n %}
{% load static from staticfiles %}
{% load statici18n %}
{% load urlhelpers %}

<header id="header">
    <div class="navbar">
        <nav class="grey darken-2">
            <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full waves-effect waves-light"><i class="material-icons">menu</i></a>
            <div class="nav-wrapper">
                <ul class="left">
                    <li>
                        <a href="{% url 'homepage' %}" class="brand-logo">linezap</a>
                    </li>
                </ul>
                <div class="search-top-bar hide-on-med-and-down">
                    <input type="search" id="search" autocomplete="false" class="autocomplete search-top-bar-input z-depth-2" name="search-state" placeholder="Search">
                    <i class="material-icons zmdi zmdi-search"></i>
                </div>
                <ul class="right hide-on-med-and-down">
                    <li>
                        <a class='dropdown-button notif-btn waves-effect waves-light' href='#' data-activates='dropdown20'><div class="i-notifications"></div> <span class="badge-green">3</span></a>
                        <ul id='dropdown20' class='notif-dropdown dropdown-content'>
                            <div id="search-hover"></div>
                            <li><a href="mail.html"><i class="zmdi zmdi-email"></i> You have 12 messages </a></li>
                            <li><a class="tabInbox" href="timeline.html"><i class="zmdi zmdi-time-countdown"></i> You have 2 upcoming activities on your Timeline </a></li>
                            <li><a href="feed.html"><i class="zmdi zmdi-notifications"></i> 3 new posts in your Feed</a></li>
                        </ul>
                    </li>
                    <li>
                        <a class='dropdown-button drop-down-profile relative-item' href='#' data-activates='dropdown3' data-beloworigin="true">
                            <span class="profile-img-ribbon"></span>
                                <img class="responsive-img profile-img" src="{% static 'images/john.png' %}" alt="john"/>
                                    <i class="zmdi zmdi-caret-down drop-down-icon"></i>
                        </a>
                        <ul id='dropdown3' class='create-dropdown dropdown-content'>
                            <li><a href="profile.html"><i class="zmdi zmdi-account-circle"></i>Profile</a></li>
                            <li><a href="calendar.html"><i class="zmdi zmdi-calendar-check zmdi-hc-fw"></i>Calendar</a></li>
                            <li><a href={% url 'logout' %}><i class="material-icons dp48">input</i>Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<script>
    $('.button-collapse').sideNav({
        menuWidth: 240, // Default is 240
        edge: 'left', // Choose the horizontal origin
        closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
    });
    $('.collapsible').collapsible();
    $('.notif-btn').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: false, // Does not change width of dropdown to that of the activator
        hover: true, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: true, // Displays dropdown below the button
        alignment: 'left' // Displays dropdown with edge aligned to the left of button
    });
    $('.drop-down-profile').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: false, // Does not change width of dropdown to that of the activator
        hover: true, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: true, // Displays dropdown below the button
        alignment: 'left' // Displays dropdown with edge aligned to the left of button
    });

    // autocomplete simulation
    var countries = [{value: "Alabama"}, {value: "Alaska"}, { value: "Arizona"}, {value: "Arkansas"}, {value: "California"},
        {value: "Colorado"}, {value: "Connecticut"}, {value: "District of Columbia"}, {value: "Delaware"}, {value: "Florida"},
        {value: "Georgia"}, {value: "Hawaii"}, {value: "Idaho"}, { value: "Indiana"}, {value: "Iowa"}, {value: "Kansas"}, {value: "Kentucky"},
        {value: "Louisiana"}, {value: "Maine"}
    ];
    var input = $('.search-top-bar #search');
    if (input.hasClass('autocomplete')) {
        var inputDiv = input.closest('div');
        var searchHtml = '<ul class="autocomplete-results hide">';
        for (var i = 0; i < countries.length; i++) {
            searchHtml += '<li class="result"><span>' + countries[i]['value'] + '</span></li>';
        }
        searchHtml += '</ul>';
        inputDiv.append(searchHtml);
        input.on('keyup', input, function() {
            var $val = input.val().trim(),
                    $select = $('.autocomplete-results');
            $select.css('width',input.width());
            if ($val != '') {
                $select.children('li').addClass('hide');
                $select.children('li').filter(function() {
                    $select.removeClass('hide');
                    var check = true;
                    for (var i in $val) {
                        if ($val[i].toLowerCase() !== $(this).text().toLowerCase()[i])
                            check = false;
                    }
                    return check ? $(this).text().toLowerCase().indexOf($val.toLowerCase()) !== -1 : false;
                }).removeClass('hide');
            } else {
                $select.children('li').addClass('hide');
            }
        });
        $('.result').click(function() {
            input.val($(this).text().trim());
            $('.result').addClass('hide');
        });
        $("#search-hover").click(function(e){
            $("#dropdown2").hide();
            $("#search").trigger("focus");
        });
    }
</script>